name: On Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: dart-lang/setup-dart@v1
      - name: Install dart dependencies
        run: dart pub get
      - name: Update Docker Images
        run: dart update_docker_images.dart force